### ISSUE TITLE
Permalink field remains empty

### ISSUE THREAD

**Issue by SimonBellucci** [mattmilburn/strapi-plugin-permalinks#22]
Hey there,

The permalink field doesn't update with the value of the `targetField` nor the `targetRelation`, it remains empty even when pressing the refresh button.

I have exactly the same configuration as provided in the documentation, and the problem occurs on Strapi 4.6.0 and 4.7.1 when `--watch-admin` mode is not enabled.

**Comment by hrenaud** [comment]
+1 same for me on `4.7.1`

**Comment by SimonBellucci** [comment]
Any update on this @mattmilburn ? At the moment this issue makes the plugin unusable. It seems to be coming from the suggestion controller, it is not sending the expected result 🤔. 

Unfortunately I don't have time to investigate this issue further.

**Comment by mattmilburn** [comment]
Hi @SimonBellucci and @hrenaud I was able to confirm this behavior and I'll be checking into this tomorrow for sure. Are you able to develop with `yarn develop --watch-admin` for now?

**Comment by SimonBellucci** [comment]
Hey @mattmilburn, thanks for looking into this concern. For now we are indeed able to develop using `yarn develop --watch admin`, since the issue only occurs when the admin is built.

**Comment by mattmilburn** [comment]
@SimonBellucci A fix will be available shortly... like within the next 30 minutes 🙂 

It turns out fetch requests enforce an absolute URL if running Strapi with `yarn develop` but you can get away with relative URLs otherwise. Certainly odd but easily worked around 👍🏻

**Comment by SimonBellucci** [comment]
Hello @mattmilburn, thanks for the fix, it works like a charm when the admin is built 🎉 However, it seems that it no longer works with `yarn develop --watch-admin` 🤔.

It throws a 404 when querying the suggestion endpoint in watch mode : `Cannot GET /permalinks/suggestion/api::page.page/Contact`.

**Comment by mattmilburn** [comment]
Yikes... thank you again @SimonBellucci I'm checking that out right now.

**Comment by mattmilburn** [comment]
@SimonBellucci The latest version of the plugin is now available which uses `strapi.backendURL` to ensure the correct API url. 👍🏻

**Comment by SimonBellucci** [comment]
Hey @mattmilburn, I was able to test this just now, and I can confirm that everything works as it should. Thanks for taking the time to resolve the issue 🙏🏻
