### ISSUE TITLE
Store formatted permalink in database

### ISSUE THREAD

**Issue by SimonBellucci** [mattmilburn/strapi-plugin-permalinks#30]
I was wondering if it is possible to store the already formatted permalink in the database? For example ```page-1/page-2``` instead of ```page-1~page-2```?

This will allow GraphQL users to access the formatted permalink in their queries, but also the use of the permalink value outside the API, for example in other custom fields.

Are there any limitations to this change and what is your opinion on this?

**Comment by mattmilburn** [comment]
Hi @SimonBellucci currently the custom field type is a `uid` which does not allow the `/` and it’s why the `~` character is used.

However I’ve been wondering if going forward the field type may change to a regular `string` type with all of the same uniqueness handling applied to it, which will then be able to store the `/` directly in the database and may improve i18n support as well.

Sorry you may have to wait a little longer for the solution to show up in a future release, but it’s something that is a high priority for this plugin.

**Comment by mattmilburn** [comment]
Hi @SimonBellucci [Version 2.0.0](https://github.com/mattmilburn/strapi-plugin-permalinks/releases/tag/v2.0.0) of this plugin is now released and no longer uses the `~` character. The plugin may still need some extra GraphQL support added in the future but this particular issue is resolved.

Please review the [migration guide](https://github.com/mattmilburn/strapi-plugin-permalinks/blob/main/MIGRATION.md) before upgrading 🙂
