### ISSUE TITLE
Internationalization bug

### ISSUE THREAD

**Issue by damian-balas** [mattmilburn/strapi-plugin-permalinks#49]
Hi @mattmilburn  :)

I've found a bug with your plugin and Internationalization. After I change the language in edit mode, the slug does not change.

1. Default language
![image](https://github.com/mattmilburn/strapi-plugin-permalinks/assets/39343843/285142b9-8768-42b5-a4e9-28af6f37e62a)
2. changed to EN language
![image](https://github.com/mattmilburn/strapi-plugin-permalinks/assets/39343843/d2bb6fb7-7b36-4acc-b2c2-221956fd9eb2)
3. refreshed the page on the EN language to "fix" the issue
![image](https://github.com/mattmilburn/strapi-plugin-permalinks/assets/39343843/391fb452-d7ea-49c7-b67d-52867929efe3)

How to reproduce:
1. create a page with a slug
2. add one different language and configure the slug too
3. refresh the page on the default language
4. change the language on the right sidebar

I think you do not have a dependency that takes the language switch into account. Check your dependency arrays in useEffect etc. 

I hope we can fix this ASAP :) 

BTW. if you don't mind, hit me up on email: damian.webdev@gmail.com
Would love to have a small conversation :) 

Thanks for the plugin!

**Comment by mattmilburn** [comment]
Hi @roberttullycarr I haven't had time to look at this in the past several months but I'd be happy to collaborate on a PR to resolve this. I'll try to take a look at it this weekend and scope out the issue.

Also, this plugin will be almost entirely re-written soon because I'm upgrading all of my plugins to Strapi 5 and TypeScript 👍🏻  So if I can fix this one issue, that may be the last commit for Strapi v4 compatibility.

**Comment by roberttullycarr** [comment]
@mattmilburn I actually was able to debug it and found a fix, how can I best share it with you?

**Comment by mattmilburn** [comment]
@roberttullycarr Great! Can you create a PR for the bug fix and we can review it and take it from there?

**Comment by roberttullycarr** [comment]
Sounds great, I will send one this weekend!

**Comment by roberttullycarr** [comment]
@mattmilburn I believe I need some access rights to push a new branch, I was able to pull the repo, but cannot push anything!

**Comment by roberttullycarr** [comment]
@mattmilburn I've done it 👍

**Comment by mattmilburn** [comment]
@roberttullycarr @damian-balas This should now be fixed in the latest [v2.2.2](https://github.com/mattmilburn/strapi-plugin-permalinks/releases/tag/v2.2.2) of this plugin.
